data:extend({
    {
        type = "bool-setting",
        name = "ulh-hotkey-starts-follow",
        setting_type = "runtime-per-user",
        default_value = false,
        order = "a",
    },
    {
        type = "bool-setting",
        name = "ulh-hotkey-remote-drives",
        setting_type = "runtime-per-user",
        default_value = true,
        order = "b",
    },
    {
        type = "bool-setting",
        name = "ulh-hotkey-picks-remote",
        setting_type = "runtime-per-user",
        default_value = true,
        order = "c",
    },
    {
        type = "int-setting",
        name = "ulh-setting-number-columns",
        setting_type = "runtime-per-user",
        default_value = 5,
        minimum_value = 1,
        maximum_value = 25,
        order = "d",
    },
    {
        type = "int-setting",
        name = "ulh-setting-number-columns-labeled",
        setting_type = "runtime-per-user",
        default_value = 0,
        minimum_value = 0,
        maximum_value = 25,
        order = "e",
    },
})
