data:extend({
    {
        type = "bool-setting",
        name = "ulh-hotkey-starts-follow",
        setting_type = "runtime-per-user",
        default_value = false,
        order = "a1",
    },
    {
        type = "bool-setting",
        name = "ulh-hotkey-remote-drives",
        setting_type = "runtime-per-user",
        default_value = true,
        order = "a2",
    },
    {
        type = "bool-setting",
        name = "ulh-hotkey-picks-remote",
        setting_type = "runtime-per-user",
        default_value = true,
        order = "a3",
    },
    {
        type = "string-setting",
        name = "ulh-create-slot-hotkey-mode",
        setting_type = "runtime-per-user",
        default_value = "insert",
        allowed_values = {"insert", "replace", "move-to-end"},
        order = "b",
    },
    {
        type = "int-setting",
        name = "ulh-setting-number-columns",
        setting_type = "runtime-per-user",
        default_value = 5,
        minimum_value = 1,
        maximum_value = 25,
        order = "c1",
    },
    {
        type = "int-setting",
        name = "ulh-setting-number-columns-labeled",
        setting_type = "runtime-per-user",
        default_value = 0,
        minimum_value = 0,
        maximum_value = 25,
        order = "c2",
    },
})
